# .goreleaser.yml
project_name: sq
builds:
  - main: ./cmd
    id: sq-server
    binary: sq-server
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    # binaries:
    #   - name: server
  - main: ./cmd/cli
    id: sq-cli
    binary: sq-cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    # binaries:
    #   - name: cli

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: adhaamehab
    name: sq

before:
  hooks:
    - go mod tidy
    - go mod download
